### ISSUE TITLE
Instructions to deploy?

### ISSUE THREAD

**Issue by Ruriko** [Rorical/Pixivel-Frontend#2]
How to install frontend & backend script?

**Comment by Rorical** [comment]
Unfortunately, we don't have the plan to write instructions for this version, because there is a newer version already in development. We prepare to write detailed instructions for the new version of the website. ( This old version running now seems terrible to me. However, if you really want to deploy it, please contact me. )

**Comment by Rorical** [comment]
The repo of new version: [https://github.com/Rorical/pixivel-front](https://github.com/Rorical/pixivel-front)

I suggest deploying this version after it is complete. It should be more beautiful with a higher performance
![image](https://user-images.githubusercontent.com/46294886/128792240-dd9bf5c6-124a-49a7-a29b-aa70bc046257.png)
